social/templates/social/dashboard_service_detail.html
social/tests/test_urls.py
social/tests/test_views.py
social/urls.py
social/views.py

Admin dashboard service detail view, url endpoint, html templates and test cases were created.

Admin Dashboard Service Detail #24

---

social/templates/social/dashboard_event_detail.html
social/tests/test_urls.py
social/tests/test_views.py
social/urls.py
social/views.py

Açıklama: Merge hatası düzeltildi.

Admin Dashboard Event Detail #33

---

CommUnitySocial/settings.py
CommUnitySocial/urls.py
dashboard_event_list/admin.py
dashboard_event_list/apps.py
dashboard_event_list/forms.py
dashboard_event_list/models.py
dashboard_event_list/templates/dashboard_event_list/eventlist.html
dashboard_event_list/tests.py
dashboard_event_list/tests/test_forms.py
dashboard_event_list/tests/test_urls.py
dashboard_event_list/tests/test_views.py
dashboard_event_list/urls.py
dashboard_event_list/views.py
landing/templates/landing/navbar.html
social/models.py

Admin Dashboard Event List feature has been added by creating a new app "dashboard_event_list" and passed the tests. A separate link to the navbar has been added for the template of the app.

Admin Dashboard Event List #37

---

dashboard_user_list/apps.py
dashboard_user_list/forms.py
dashboard_user_list/templates/dashboard_user_list/userlist.html
dashboard_user_list/urls.py
dashboard_user_list/views.py

Admin dashboard member_list is done !!

Admin Dashboard Member List #27

---

social/templates/social/dashboard_event_detail.html
social/templates/social/dashboard_service_detail.html
social/views.py

Admin Dashboard Service and Event Detail #24 #33

---

social/templates/social/dashboard_event_detail.html
social/templates/social/dashboard_service_detail.html

[BUG] Servicelist Detail page does not show rejected applicants.
[BUG] Eventlist Detail page does not show rejected applicants.
[BUG] Service Detail Page Admin users cannot see pending applicants
[BUG] Event Detail Page Admin users cannot see pending applicants
[BUG] Servicelist Detail Applicant's Profile link
[BUG] Eventlist Detail Applicant's Profile link
Info: Bugs are fixed.

Servicelist Detail and Eventlist Detail fixes

---

social/templates/social/dashboard_event_detail.html
social/templates/social/dashboard_service_detail.html

application status is fixed on admin dashboard

application status is fixed on admin dashboard

---

landing/templates/landing/index.html
social/templates/social/allevents.html
social/templates/social/allservices.html
social/templates/social/appliedevents.html
social/templates/social/appliedservices.html
social/templates/social/createdevents.html
social/templates/social/createdservices.html
social/templates/social/event-search.html
social/templates/social/mylikes.html
social/templates/social/service-filter.html
social/templates/social/service-search.html
social/templates/social/timeline.html
social/templates/social/usersevents.html
social/templates/social/usersservices.html

Datetime labels edited for services and events

---

dashboard_user_list/forms.py
dashboard_user_list/templates/dashboard_user_list/userlist.html
dashboard_user_list/views.py

User dashboard bugs is solved.

User Dashboard Bugs Solved #95 #96 #97 #98 #99

---

social/views.py

Note: Improvement is completed.

Search result showing algorithm #119

---

dashboard_user_list/templates/dashboard_user_list/userlist.html
dashboard_user_list/views.py

user bugs solved #95 #96 #97 #98 #99

---

dashboard_event_list/templates/dashboard_event_list/eventlist.html
dashboard_event_list/views.py
dashboard_service_list/templates/dasboard_service_list/servicelist.html
dashboard_service_list/views.py
social/views.py

Fixed failure in finding some keywords in search. Added title to admin Service and Event list pages. Added placeholder to Event search bar. Provided maintaining the last searched keyword in admin search bars. Enhanced the layout of query fields in admin Service and Event lists.

Bug and Enhancement for Admin, Services and Events Search #178

---

CommUnitySocial/.env

New db connection added to env file.

env file changed for db #192

---

social/templates/social/event_detail.html
social/templates/social/service_detail.html

Found word changed to yet for applications on detail pages.

Found word changed to yet #202

---

social/templates/social/profile.html

Only super admin can make and remove admin. Super admin can now see super admin tag too.

Super admin implemented for add remove admin #174

---

social/templates/social/admindashboardindex.html

Index text is removed from admin dashboard page.

Admin dashboard index text removed

---

dashboard_service_list/templates/dasboard_service_list/servicelist.html
dashboard_service_list/views.py

After submitting the form on the admin service list page, the admin shall be able to see previously selected options. The admin shall be able to search for location with Turkish lower case letters.

Enhance Admin Service List Filters #252

---

social/views.py

The user can search for an Event or Service with lower case letters in the address.

Bug in Search for Turkish Characters #191

---

dashboard_event_list/views.py
dashboard_service_list/views.py

Bug for sorting names with lower case letters has been fixed.

Bug in name sorting #262

---

social/views.py

[BUG] Smart sorting crash #269 Note: Crash is fixed.

---

landing/templates/landing/navbar.html
social/templates/social/service-search.html
social/views.py

Category filter and search bar are working together. Services option in Navbar links to Service Search page.

Combine Filter and Search Buttons on All Services Page #198

---

social/templates/social/service-search.html
social/views.py

Users shall be able sort services according to name, creation date, delivery date and rating.

Sort Services #257

---

landing/templates/landing/navbar.html

Navbar button UI corrected and admin dashboard dropdown removed.

Nav buttons and admin dropdown #277 #282

---

social/views.py

Complainted text is corrected.

Complainted text is corrected #281

---

wiki/views.py

redirect to wiki

---

social/views.py

The bug has been fixed. Default Services page shows all the categories now.

Services Page Default Category #306

---

social/templates/social/profile.html

[BUG] Other Profile Interest Add Remove Buttons #315

---

social/templates/social/service-search.html
social/views.py

Pagination with 5 items per page has been added to Services page.

Pagination to All Services Page #196

---

social/forms.py
social/templates/social/service-search.html
social/views.py

Location search for services from the map with optional distances has been added.

Location and Search - Sort Related Improvements

---

dashboard_service_list/templates/dasboard_service_list/servicelist.html
dashboard_service_list/views.py

A separate search bar has been added to Adm Service Page so that admin shall be able to search services with an address keyword.

Separate Search Bar for Location in Adm Service Page #348

---

dashboard_event_list/templates/dashboard_event_list/eventlist.html
dashboard_event_list/views.py

A separate search bar has been  to Adm Event Page so that admin shall be able to search events with an address keyword.

Separate Search Bar for Location in Adm Event Page #350

---

social/templates/social/allusers.html
social/views.py

Pagination has been added to All Users page with ten items per page.

Pagination to All Users Page #322

---

landing/views.py
social/views.py

[BUG] Recommendation for new users #358

---

landing/templates/landing/navbar.html

color change on navbar

---

social/templates/social/map.html
social/templates/social/service-search.html
social/urls.py
social/views.py

Location search with map is now working with pagination. For map search there's a link for map page. Address search is also possible with entering a keyword in the search bar besides map search.

Pagination to All Services Page #196 with map search

---

landing/templates/landing/navbar.html
social/templates/social/event-search.html
social/templates/social/map.html
social/templates/social/service-search.html
social/views.py

Sort, pagination and search by map features have been added to Events page.

Location and Search - Sort Related Improvements #332

---

social/views.py

Smart Search and Pagination Combining Error #356

---

dashboard_service_list/templates/dasboard_service_list/servicelist.html
dashboard_service_list/views.py

Admin shall be able to filter open services (services that can be applied).

Filter Dropdown Only Actives for Events #287

---

social/views.py

Key Error Bug in Services Page #369

---

social/templates/social/service_edit.html
social/views.py
wiki/templates/wiki/wiki_ser_desc_edit.html
wiki/urls.py
wiki/views.py

A user is able to edit wiki description while editing a service.

Retrieve Wikidata description while editing a Service #189

---

social/templates/social/event_edit.html
social/views.py
wiki/templates/wiki/wiki_event_desc_edit.html
wiki/urls.py
wiki/views.py

A user is able to change or add wiki description while editing en event.

Retrieve Wikidata description while editing an Event #190

---

landing/templates/landing/navbar.html

Change Recommendation Menu Color #357

---

dashboard_event_list/views.py
dashboard_service_list/views.py

Number of items per page in pagination have been set to 10.

Pagination 10 for ALL Pages #321

---

dashboard_event_list/tests/test_views.py

3 new unit tests have been added.

Add New Tests to Admin Event List Feature #385

---

social/views.py

[BUG] - Services page loads in 9 minutes... #381

---

landing/views.py

Note: Improvement is completed.

3 Random Service Event on Main Page #391

---

social/management/commands/createdata.py

Now works on both windows and macos

[BUG] Faker Createdata is not working on MacOS #393

---

landing/views.py
social/views.py

Recommendation Slowness Problem #389
Do not show recommendation after dislike #388
Note: Bugs are fixed.

Like Dislike Increase Decrease Problem #390

---

social/templates/social/service-search.html
social/views.py

[BUG] Service search 'sort by' feature does not work with pagination #408

---

social/templates/social/profile.html
social/views.py

[BUG] Interest <everest> cannot be removed from the profile page #401

---

social/templates/social/service-search.html
social/views.py

A user is now able to search a service with location from the map on the Services page without going to a separate map page.

Bring the Map to Service Search Page #412

---

social/views.py

[BUG] Service Like and Application ineffective in interest #417
[BUG] Recommendations are served in reverse order #418
Note: Bug is fixed.

[BUG] - Recommendation like multiplies the recommended services #405

---

social/views.py

[BUG] Service search by category fails at pagination #422

---

dashboard_user_list/templates/dashboard_user_list/userlist.html
dashboard_user_list/views.py

bug and search #399 #400

---

social/templates/social/complaint.html
social/templates/social/complaintAdminSide.html
social/templates/social/complaintsDoneByMe.html
social/templates/social/mycomplaints.html
social/views.py

Complaint page changes are done.

[BUG] Non-admin users can solve their own complaints instead of editing/deleting #426

---

social/templates/social/event-search.html
social/views.py

Date sort in Event and Service pages have been made uniform.

Make date sorting uniform for Event and Service #436

---

social/views.py

Complaint bugs described in the issue are solved. The edit, delete and solve functions are redirected is solved or deleted before.

Complaint bugs #445

---

social/views.py

[BUG] Smart search priorities follow and rating do not work. #447

---

social/views.py

Errors are solved for service and events.

Communication notification errors solved #450 #451

---

landing/views.py

[BUG] Approved Recommendation Not Shown As Approved on Main Page #453

---

social/templates/social/event-search.html
social/templates/social/service-search.html
social/views.py

10 KM range is added as default range.

No Services Result when Distance is not selected #455

---

landing/templates/landing/index.html
landing/views.py

[BUG] Main page recommendation bug #457

---

social/tests/test_urls.py
social/tests/test_views.py

Tests are added to views and urls files.

Update Tests #461
